import { ThemeProviderConfig } from "@/components/ThemeProviderConfig";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { MobileHeader } from "@/components/MobileHeader";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portfolio | Huynh Dang Khoa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} h-[300vh] bg-[#34353a] antialiased dark:bg-white`}
      >
        <ThemeProviderConfig
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <MobileHeader />

          <main>{children}</main>

          <Footer />
          <Toaster
            toastOptions={{
              // unstyled: true,
              classNames: {
                error: "bg-red-400",
                success: "text-green-600 ",
                warning: "text-yellow-400",
                info: "bg-blue-400",
              },
            }}
          />
        </ThemeProviderConfig>
      </body>
    </html>
  );
}
